name: My Workflow
on: [pull_request]

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get git diff
      run: |
        pip install openai
        git_diff=$(git diff ${{ github.base_ref }}...${{ github.head_ref }})
        echo "::set-output name=git_diff::$git_diff"
      shell: bash

    - name: My Python action
      uses: GilbertGomez94/chatgpt-pr-review/.github/actions/pr_checker
      id: custom_step
      with:
        prompt: ${{ steps.get_git_diff.outputs.git_diff }}

